---
auth_file: ~/.octoauth.d/spaarti.yml
base_path: '~/src'
purge: true
quiet: true
formats:
  - match: -archived/
    path: trash/%<full_name>s
exclude:
  full_name:
  - ^[pt]
  - ^mlo
  name:
  - ^draft-
