#!/bin/bash

for zoneFile in $(ls /etc/nsd/*.zone) ; do
  oldSerial="$(awk '/serial number/ {print $1}' $zoneFile)"
  theDate="$(date +%Y%m%d)"
  if [ "${oldSerial::-2}" -lt "$theDate" -o "$1" == "reset" ] ; then
    newSerial="${theDate}00"
  elif [ "${oldSerial:(-2)}" == "99" ] ; then
      let newSerial=(${oldSerial::-2}+1)*100 
  else
      let newSerial=$oldSerial+1
  fi
  #echo "$zoneFile: $newSerial"
  sed -i "s/$oldSerial ; serial number/$newSerial ; serial number/" $zoneFile
done

if [ -z "$1" ] ; then
  nsdc rebuild > /dev/null
  nsdc reload > /dev/null
  nsdc notify 2>&1 | grep -v -e "timeout ([0-9] s) expired" -e "^Sending notify"
fi

